### ISSUE TITLE
Promise.all()不能确保所有promise都被执行完成

### ISSUE THREAD

**Issue by leijianning** [ygm125/promise#1]
测试代码：
var a = Promise.resolve(1);
var b = Promise.delay(2000, 2);
var c = Promise.delay(1000, 3);
var d = Promise.resolve(4);
var e = Promise.resolve(5);
Promise.all([a,b,c,d,e]).then(function(result) {
    console.log(result);
});

执行结果：
[ 1, , , 4, 5 ]

**Comment by ygm125** [comment]
计数方式不对，已处理
